-- Shared provisioning for first NEAR login and wallet binding. The user row lock
-- serializes both paths, and the caller's transaction includes all provisioning.
CREATE OR REPLACE FUNCTION ensure_near_personal_organization(wallet_user_id UUID) RETURNS UUID
LANGUAGE plpgsql AS $$
DECLARE
    personal_org UUID;
    account_name TEXT;
    membership_time TIMESTAMPTZ;
    generated_name TEXT;
    inserted_org UUID;
BEGIN
    SELECT provider_user_id INTO account_name FROM users
      WHERE id = wallet_user_id AND auth_provider = 'near' AND is_active FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Active NEAR identity required';
    END IF;
    SELECT o.id INTO personal_org FROM organization_members m
      JOIN organizations o ON o.id = m.organization_id AND o.is_active
      WHERE m.user_id = wallet_user_id AND m.role = 'owner'
      ORDER BY m.joined_at, m.organization_id LIMIT 1;
    IF FOUND THEN RETURN personal_org; END IF;

    personal_org := uuid_generate_v4();
    -- Defaults are inferred from the first membership. Also repair identities
    -- invited before provisioning, and avoid equal NOW() values within one tx.
    SELECT LEAST(now(), COALESCE(min(joined_at), now())) - interval '1 microsecond'
      INTO membership_time FROM organization_members WHERE user_id = wallet_user_id;
    LOOP
        generated_name := left(account_name, 246) || '-org-' || left(uuid_generate_v4()::text, 4);
        INSERT INTO organizations(id, name) VALUES(personal_org, generated_name)
          ON CONFLICT(name) WHERE is_active = true DO NOTHING RETURNING id INTO inserted_org;
        EXIT WHEN inserted_org IS NOT NULL;
    END LOOP;
    INSERT INTO organization_members(organization_id, user_id, role, joined_at)
      VALUES(personal_org, wallet_user_id, 'owner', membership_time);
    INSERT INTO workspaces(name, organization_id, created_by_user_id)
      VALUES('default', personal_org, wallet_user_id);
    RETURN personal_org;
END;
$$;

-- Shorten only untouched names generated by V0092, preserving custom names.
DO $$
DECLARE
    old_org RECORD;
    generated_name TEXT;
BEGIN
    FOR old_org IN
        SELECT o.id, u.provider_user_id AS account_name
        FROM organizations o
        JOIN organization_members m ON m.organization_id = o.id AND m.role = 'owner'
        JOIN users u ON u.id = m.user_id AND u.auth_provider = 'near'
        WHERE o.name = left(u.provider_user_id, 210) || '-org-' || o.id::text
    LOOP
        LOOP
            generated_name := left(old_org.account_name, 246) || '-org-' || left(uuid_generate_v4()::text, 4);
            BEGIN
                UPDATE organizations SET name = generated_name, updated_at = now() WHERE id = old_org.id;
                EXIT;
            EXCEPTION WHEN unique_violation THEN
                -- Another organization already uses this suffix; choose a new one.
                NULL;
            END;
        END LOOP;
    END LOOP;
END;
$$;
