providers:
  - name: "vllm-prod-1"
    type: "vllm"
    url: "http://160.72.54.186:8000"
    api_key: "secret123"
    enabled: true
    priority: 1
  - name: "vllm-prod-2"
    type: "vllm"
    url: "http://50.148.213.234:8000"
    api_key: "secret123"
    enabled: true
    priority: 2

server:
  host: "0.0.0.0"
  port: 3000

model_discovery:
  refresh_interval: 300
  timeout: 30

logging:
  level: "debug"
  format: "compact"
  modules:
    api: "debug"
    services: "debug"

dstack_client:
  url: "http://localhost:8000"

# Authentication configuration with both providers
auth:
  mock: true
  
  # GitHub OAuth Configuration Example
  # 
  # To use GitHub OAuth:
  # 1. Go to https://github.com/settings/developers
  # 2. Create a new OAuth App
  # 3. Set Authorization callback URL to: http://localhost:3000/v1/auth/callback
  # 4. Copy Client ID and Client Secret
  github:
    client_id: "Ov23liu1DaGN6i5o8DwW"
    client_secret: "77c835278ff4a9411f3f4267e1f1d37080a9dda1"
    redirect_url: "http://localhost:3000/v1/auth/callback"

database:
  host: "postgres"  # Docker service name
  port: 5432
  database: "platform_api"
  username: "postgres"
  password: "postgres"
  max_connections: 5
