providers:
  - name: "vllm-prod-1"
    type: "vllm"
    url: "http://0.0.0.1:8000"
    api_key: "my-api-key"
    enabled: true
    priority: 1

server:
  host: "0.0.0.0"
  port: 3000

model_discovery:
  refresh_interval: 300
  timeout: 30

logging:
  level: "info"
  format: "pretty"
  modules:
    api: "info"
    domain: "info"

dstack_client:
  url: "http://localhost:8000"


# Authentication configuration with both providers
auth:
  enabled: true

  github:
    client_id: "YOUR_GITHUB_CLIENT_ID"
    client_secret: "YOUR_GITHUB_CLIENT_SECRET"
    redirect_url: "http://localhost:3001/auth/callback"  # Frontend callback URL
  

  google:
    client_id: "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
    client_secret: "YOUR_GOOGLE_CLIENT_SECRET"
    redirect_url: "http://localhost:3001/auth/callback"  # Frontend callback URL