use_mock: false

providers:
  - name: "vllm-prod-1"
    type: "vllm"
    url: "http://0.0.0.1:8000"
    api_key: "my-api-key"
    enabled: true
    priority: 1

server:
  host: "0.0.0.0"
  port: 3000

model_discovery:
  refresh_interval: 300
  timeout: 30

logging:
  level: "info"
  format: "pretty"
  modules:
    api: "info"
    domain: "info"

dstack_client:
  url: "http://localhost:8000"


# Authentication configuration with both providers
auth:
  enabled: true
  
  # GitHub OAuth Configuration Example
  # 
  # To use GitHub OAuth:
  # 1. Go to https://github.com/settings/developers
  # 2. Create a new OAuth App
  # 3. Set Authorization callback URL to: http://localhost:3000/auth/callback
  # 4. Copy Client ID and Client Secret
  github:
    client_id: "YOUR_GITHUB_CLIENT_ID"
    client_secret: "YOUR_GITHUB_CLIENT_SECRET"
    redirect_url: "http://localhost:3000/auth/callback"
  
  # Google OAuth Configuration Example
  # 
  # To use Google OAuth:
  # 1. Go to https://console.cloud.google.com/apis/credentials
  # 2. Create a new OAuth 2.0 Client ID
  # 3. Add http://localhost:3000/auth/callback to Authorized redirect URIs
  # 4. Copy Client ID and Client Secret
  google:
    client_id: "YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com"
    client_secret: "YOUR_GOOGLE_CLIENT_SECRET"
    redirect_url: "http://localhost:3000/auth/callback"