# Mock Provider Configuration
# Use for testing and development without real vLLM servers
# No authentication required in this mode

use_mock: true

# No providers needed - mock service handles all requests
providers: []

server:
  host: "0.0.0.0"
  port: 3000

# Mock mode doesn't need model discovery
model_discovery:
  refresh_interval: 0
  timeout: 5

logging:
  level: "debug"
  format: "pretty"
  modules:
    api: "trace"
    domain: "debug"

dstack_client:
  url: "http://localhost:8000"

# Authentication disabled for development
auth:
  enabled: false